### ISSUE TITLE
Create Setup Dialog via eclipse plugin

### ISSUE THREAD

**Issue by steffen-wilke** [gurkenlabs/litiengine-eclipse-plugin#1]
![image](https://user-images.githubusercontent.com/7015370/51049262-aa3b4200-15cd-11e9-94a5-1d5da6e4e2f2.png)

- Title 
- Subtitle
- Icon
- Other `GameInfo` stuff
- Base package
- Game class (application entry point)
- project location

**Comment by waitwathuh** [comment]
@steffen-wilke @nightm4re94 
I would like to pick up this issue, please.

I have created a UI that I think has all the necessary fields. Please let me know if you'd like me to make changes.

<img width="681" alt="Screenshot 2023-09-30 at 00 05 21" src="https://github.com/gurkenlabs/litiengine-eclipse-plugin/assets/14177221/e68d7c8e-fef6-4cc3-9e4c-a7683206ef0a">

**Comment by steffen-wilke** [comment]
Thank you for your engagement. 
Going back to this issue after almost five years, a lot has changed with the engine and the Java ecosystem.

Honestly, I think a wizard for setting up a LITIENGINE game is still a nice addition to the engine but from where we are today, this should probably be **IDE-independent** or maybe **integrated into the utiLITI** editor instead of only being available for Eclipse.
@nightm4re94 thoughts?

However, that being said: I think there would still be value in an Eclipse solution for this.
Regarding the UI: I think that looks good. Maybe we don't need Ant anymore? I think it is also more about what exactly gets initialized and all these fields probably also need good defaults and should not be blank,

**Comment by nightm4re94** [comment]
At this point, the need for an Eclipse plugin has shrunk down quite drastically.
Certainly, we should strive to optimize the project setup experience with utiLITI instead.
Ideally, the engine should be agnostic of the used IDE and an Eclipse plugin seems like yet another rather unrelated workpackage to maintain. 
Thanks so much for the effort you've put into the mockup, but I'd prefer closing this issue as not planned.
